### ISSUE TITLE
Canopy Class QA Checks (Prism Plot)

### ISSUE THREAD

**Issue by chrishawes9** [ForestManagementGeodatabase/fmgpy#12]
Need to add a series of QA Checks on canopy classes and diameters. Flag rows that violate rules. Target FC is Prism Plots
1. Flag all trees with a diameter more than 50 inches across all canopy classes
2. Flag all trees with a diameter more than 18 inches that are canopy class: intermediate
3. Flag all trees with a diameter less than 12 inches that are canopy class: co-dominant
4. Flag all trees with a diameter less than 30 inches that are canopy class: dominant

**Comment by aross26** [comment]
Added checks to _check_required_fields_prism_
