### ISSUE TITLE
QA needed on AGE_ORG values

### ISSUE THREAD

**Issue by chrishawes9** [ForestManagementGeodatabase/fmgpy#7]
The AGE_ORG field in the Age_Plot feature class needs to have valid 4 digit years. It cannot have partial years or a value of 0. These types of values impact the mean age calculation that occurs in the summary code. Having zero values or two digit years artificially lowers the mean age for a given site or stand. Null is a valid replacement for 0.

**Comment by aross26** [comment]
added a check to the "Check Required Fields" tool which populates a "VALID_AGE" field: ages >=1500 are valid, less than that or None are invalid
